// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvsocrbmehiiciondxno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2c29jcmJtZWhpaWNpb25keG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwODU0MzIsImV4cCI6MjA2MDY2MTQzMn0.YTsgHeMdQPV9dTfcjFNjhu_QdggSqwyN7CfpghhFFQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);